version: "3.9"
services:
  orderdb:
    container_name: orderdb
    restart: always
    ports:
      - "1433:1433"
    volumes:
      - orderdb_volume:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password12*